apiVersion: v1
kind: Pod
metadata:
  name: my-kubernetes-dashboard

spec:
  containers:
    - name: my-kubernetes-dashboard
      image: my-kubernetes-dashboard
  serviceaccountName: dashboard-sa   # ✅ This assigns the custom service account 
   
# This tells Kubernetes: “Use the dashboard-sa ServiceAccount instead of the default one.”     

#kubectl create -f pod-definition.yml
# kubectl get serviceaccount
# kubectl describe pod my-kubernetes-dashboard
