apiVersion: v1
kind: Pod
metadata:
  name: python-app
  labels:
    app: python-app         # Must match the selector in the Service
spec:
  containers:
    - name: python
      image: python:3.11
      ports:
        - containerPort: 80
