apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
#  hostPath:
#    path: /tmp/data # this option for path is not to be used in a prod env
  awsElasticBlockStore:
    volumeID: <volume-id>
    fsType: ext4

# kubectl create -f pv-definition.yml
# kubectl get persistentvolume